### ISSUE TITLE
USER PROGRESS

### ISSUE THREAD

**Issue by haithamRD** [devianl2/laravel-scorm#13]
Hi @devianl2 

have any update to track user sco for any module uploaded and how to save this data in database if u had any information about this u can explain how to use it

thank you

**Comment by CThomas87** [comment]
If possible I'd like to see an example of user tracking works too.

**Comment by devianl2** [comment]
@CThomas87 In order for you to track user progress from scorm, you have to implement an IFRAME with sort of javascript to read the variable from SCORM package. This package is focus on SCORM package extraction and function to store user learning progress. You may read the article below to get some ideas how to sync SCORM information from frontend to backend.

https://scorm.com/scorm-explained/technical-scorm/run-time/?utm_source=google&utm_medium=natural_search

**Comment by devianl2** [comment]
I do not see any further reply. This post is mark as closed now. If you have any question in future, feel free to open another post. Thank you
