### ISSUE TITLE
save progress

### ISSUE THREAD

**Issue by haithamrdina** [devianl2/laravel-scorm#16]
hi [@devianl2
there are no examples for saving progress ?
if you can make an example to see how do it 
thanks

**Comment by devianl2** [comment]
Hi @haithamrdina,

I assume you know how to receive cmi data from iframe, submit through ajax to API. I will share some code below for your reference.

1) First of all, you need to have retrieve the sco ID and sco tracking ID. (I assume you have it)
2) Submit cmi data with sco ID and sco tracking ID.
3) Use the code below to find user sco tracking.
`$scoTracking    =   ScormManager::findScoTrackingId($scoUuid, $scoTrackingUuid);`

4) Update user learning with the following code:
`$sco    =   ScormManager::updateScoTracking($scoUuid, $scoTracking->user_id, $this->request->input('cmiData'));

if ($sco->lesson_status ==  'completed' || $sco->lesson_status == 'passed') {
   // Update learner's learning record from your own LMS function (Telling the LMS the user is completed the scorm)
}
`

**Comment by haithamrdina** [comment]
thanks you so much @devianl2  if u can share with me some reference  to receive cmi data from iframe,

**Comment by baskarcm** [comment]
how to receive cmi data(lesson_location) from iframe for every current lesson.

**Comment by zaks-zaiya** [comment]
Do you have an example how to play the scorm after upload.
So far Im already success on upload part. But still no idea how to show, play and track progress.

**Comment by devianl2** [comment]
> Do you have an example how to play the scorm after upload. So far Im already success on upload part. But after that, no idea how to show, play and track progress.

Hi @zaks-zaiya , that is beyond the scope of this package. But to answer your question, you need to know how to use iframe and postMessage to transmit the CMI message into API.

1. You need to have understand the hierarchy of iframes: https://scorm.com/scorm-explained/technical-scorm/run-time/
2. Use **postMessage** to parse your uploaded scorm file url and learner data into children iframe: https://javascript.info/cross-window-communication#postmessage
3. Use frontend scorm library to parse and listen to scorm data, and use postMessage to parse scorm respond back to parent iframe: https://www.npmjs.com/package/scorm-again
4. Any respond that is being captured by parent iframe postMessage listener will send to your POST request API (From your laravel route)

This package is mainly focus on SCORM file upload, extract, create SCO data and learner data. It does not cover frontend listener :)

If you need help on frontend iframe listener, please email to devianleong@gmail.com. I will try my best to reply in shortest time.
