### ISSUE TITLE
SCORM zip file import issue

### ISSUE THREAD

**Issue by rhnkyr** [devianl2/laravel-scorm#18]
Hi,

I am using https://21w98o3yqgi738kmv7xrf9lj-wpengine.netdna-ssl.com/wp-content/assets/golf_examples/PIFS/RuntimeBasicCalls_SCORM12.zip as example and lib throws error as invalid_scorm_archive_message

Looks like on Manager/ScormManager.php L:48 the $zip->getStream('imsmanifest.xml') call returns false event thought the file is there.

Any idea?

Thanks in advance.

**Comment by devianl2** [comment]
Hi there, I found out that some 

> Hi,
> 
> I am using https://21w98o3yqgi738kmv7xrf9lj-wpengine.netdna-ssl.com/wp-content/assets/golf_examples/PIFS/RuntimeBasicCalls_SCORM12.zip as example and lib throws error as invalid_scorm_archive_message
> 
> Looks like on Manager/ScormManager.php L:48 the $zip->getStream('imsmanifest.xml') call returns false event thought the file is there.
> 
> Any idea?
> 
> Thanks in advance.

Does your server have the [ZIP extension](https://www.php.net/manual/en/zip.requirements.php) installed/enabled? Check with phpinfo()

**Comment by devianl2** [comment]
> Hi there, I found out that some
> 
> > Hi,
> > I am using https://21w98o3yqgi738kmv7xrf9lj-wpengine.netdna-ssl.com/wp-content/assets/golf_examples/PIFS/RuntimeBasicCalls_SCORM12.zip as example and lib throws error as invalid_scorm_archive_message
> > Looks like on Manager/ScormManager.php L:48 the $zip->getStream('imsmanifest.xml') call returns false event thought the file is there.
> > Any idea?
> > Thanks in advance.
> 
> Does your server have the [ZIP extension](https://www.php.net/manual/en/zip.requirements.php) installed/enabled? Check with phpinfo()

Also, check if the zip module is working in your server:
https://stackoverflow.com/questions/69853899/zip-module-not-loading-php-8-0-12
