### ISSUE TITLE
Add an example how to use it

### ISSUE THREAD

**Issue by kr-apps** [devianl2/laravel-scorm#2]
Hi,

It would be great to have and example how to use it. I have looked in the code but I'm a beginner and I found kind of difficult how to get started.

By the way the package is very interesting.

**Comment by devianl2** [comment]
Hi there, sorry for late reply. I am having difficulty to write a complete documentation during this pandemic. However, I will try to come out a documentation to assist those who need SCORM in laravel.

> Hi,
> 
> It would be great to have and example how to use it. I have looked in the code but I'm a beginner and I found kind of difficult how to get started.
> 
> By the way the package is very interesting.

**Comment by rhnkyr** [comment]
@devianl2 any update?

**Comment by devianl2** [comment]
@rhnkyr @kr-apps Updated documentation
