### ISSUE TITLE
Basic example of uploaded scorm to iframe and tracking user data

### ISSUE THREAD

**Issue by MeesPos** [devianl2/laravel-scorm#20]
Does anyone have an example to put the uploaded course in an iframe, and track the user data?

**Comment by devianl2** [comment]
Hi @MeesPos , that is beyond the scope of this package. But to answer your question, you need to know how to use iframe and postMessage to transmit the CMI message into API.

You need to have understand the hierarchy of iframes: https://scorm.com/scorm-explained/technical-scorm/run-time/
Use postMessage to parse your uploaded scorm file url and learner data into children iframe: https://javascript.info/cross-window-communication#postmessage
Use frontend scorm library to parse and listen to scorm data, and use postMessage to parse scorm respond back to parent iframe: https://www.npmjs.com/package/scorm-again
Any respond that is being captured by parent iframe postMessage listener will send to your POST request API (From your laravel route)
This package is mainly focus on SCORM file upload, extract, create SCO data and learner data. It does not cover frontend listener :)

If you need help on frontend iframe listener, please contact me personally ([devianleong@gmail.com](mailto:devianleong@gmail.com)). I will create a simple demo for you. Just buy me a coffee :)

**Comment by MeesPos** [comment]
I fixed it, thanks!

**Comment by haithamrdina** [comment]
@MeesPos 
hi , 
you can share the part of code please
