### ISSUE TITLE
Issue missing identifier column 

### ISSUE THREAD

**Issue by AmrAbdalrahman** [devianl2/laravel-scorm#25]
according to the last merged [PR](https://github.com/devianl2/laravel-scorm/pull/21/files#diff-d1bee73376269984dc8c1f56bffd55fd167c70ebf1d81a089cb128efffbf7a51) 

 for  [ScormManager.php](https://github.com/devianl2/laravel-scorm/blob/f12d58455f0df4db329d941a5a7f318a74995da3/src/Manager/ScormManager.php#L154) you define a new column called `identifier` while save a new created scorm however isn't defined at [create_scorm_tables.php.stub](https://github.com/devianl2/laravel-scorm/blob/main/database/migrations/create_scorm_tables.php.stub) migration and  [ScormModel.php](https://github.com/devianl2/laravel-scorm/blob/main/src/Model/ScormModel.php)

**Comment by devianl2** [comment]
Hi @AmrAbdalrahman ,

Thanks for the highlight. The column has been added in version 4 and main repo. I will add it in version 3 soon.

Regards,
Dev
