### ISSUE TITLE
Using the Package

### ISSUE THREAD

**Issue by samuelsituma** [devianl2/laravel-scorm#3]
Hello, @devianl2  this is a great package do you have an example of how this can be used?

**Comment by devianl2** [comment]
> Hello, @devianl2 this is a great package do you have an example of how this can be used?

Hi there, sorry for late reply. I am having difficulty to write a complete documentation during this pandemic. However, I will try to come out a documentation to assist those who need SCORM in laravel.

**Comment by samuelsituma** [comment]
Well noted @devianl2  we will appreciate, Thank you.
